# 1.1 Создание вектора

In [1]:
#Требуется создать вектор

In [7]:
import numpy as np
#Создать вектор как строку
vector_row = np.array([1, 2, 3])
print('Создание вектора в виде строки ', vector_row)
vector_column = np.array([
    [1],
    [2],
    [3]
])
print('Создание вектора как столбец\n', vector_column)

Создание вектора в виде строки  [1 2 3]
Создание вектора как столбец
 [[1]
 [2]
 [3]]


In [10]:
print('Превращение столбца в строку через транспонирование', vector_column.T)

Превращение столбца в строку через транспонирование [[1 2 3]]


# 1.2 Создание матрицы

In [11]:
#Требуется создать матрицу

In [17]:
import numpy as np
#Создать матрицу
matrix = np.array([
    [1, 2],
    [1, 2],
    [1, 2]
])
print('Созданная матрица\n', matrix)

Созданная матрица
 [[1 2]
 [1 2]
 [1 2]]


In [20]:
#Не рекомендуется использовать матричную структуру
matrix_object = np.mat([
    [1, 2],
    [1, 2],
    [1, 2]
])
print('Созданная матрица без array\n', matrix_object)

Созданная матрица без array
 [[1 2]
 [1 2]
 [1 2]]


# 1.3 Создание разряженной матрицы

In [ ]:
#Имеются данные с очень малым количеством ненулевых значений, которые требуется эффективно представить

In [5]:
import numpy as np
from scipy import sparse
matrix = np.array([
    [0, 0],
    [0, 1],
    [3, 0]
])
#Создаем сжатую разряженную матрицу-строку (CSR - матрицу)
matrix_sparse = sparse.csr_matrix(matrix)
print('matrix_sparse=\n', matrix_sparse)

matrix_sparse=
   (1, 1)	1
  (2, 0)	3


# 1.4 Выбор элементов

In [1]:
#Требуется выбрать один или несколько элементов  в векторе или матрице

In [6]:
import numpy as np
vector = np.array([1, 2, 3, 4, 5, 6])
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
#выбрать третий элемент вектора
vector[2]

3

In [7]:
#выбрать вторую строку второй столбец матрицы
matrix[1, 1]

5

In [8]:
#выбрать все элементы вектора
vector[:]

array([1, 2, 3, 4, 5, 6])

In [9]:
#выбрать все впроть до третьего элемента включительно
vector[:3]

array([1, 2, 3])

In [10]:
#выбрать все после третьего элемента 
vector[3:]

array([4, 5, 6])

In [11]:
#выбрать последний элемент
vector[-1]

6

In [12]:
#выбрать первые две строки и все столбцы матрицы
matrix[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
#выбрать все строки и второй столбец
matrix[:, 1:2]

array([[2],
       [5],
       [8]])

# 1.5 Описание матрицы

In [ ]:
#Требуется описать форму, размер и размерность матрицы

In [ ]:
#использовать shape, size, ndim

In [1]:
import numpy as np
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

In [2]:
#взглянуть на количество строк и столбцов
matrix.shape

(3, 4)

In [3]:
#взглянуть на количество элементов
matrix.size

12

In [4]:
#взглянуть на количество размерностей
matrix.ndim

2

# 1.6 Применение операций к элементам

In [ ]:
#Требуется применить некоторую функцию к нескольким элементам массива

In [5]:
import numpy as np
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [6]:
#Создать функцию
add_100 = lambda i: i + 100
#Создать векторизованную функцию
vectorized_add_100 = np.vectorize(add_100)

In [7]:
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [8]:
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

# Нахождение максимального и минимального значений

In [ ]:
#Требуется найти максимальное и минимальное значение в массиве

In [1]:
import numpy as np
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [2]:
np.max(matrix)

9

In [3]:
np.min(matrix)

1

In [4]:
#максимальный элемент в каждом столбце
np.max(matrix, axis=0)

array([7, 8, 9])

In [5]:
#максимальный элемент в каждой строке
np.max(matrix, axis=1)

array([3, 6, 9])

In [6]:
matrix = np.array([
    [1, 7, 4],
    [3, 9, 6],
    [2, 8, 5]
])
#максимальный элемент в каждом столбце
np.max(matrix, axis=0)

array([3, 9, 6])

In [7]:
matrix = np.array([
    [1, 7, 4],
    [3, 9, 6],
    [2, 8, 5]
])
#максимальный элемент в каждой строке
np.max(matrix, axis=1)

array([7, 9, 8])

# Вычисление среднего значения, дисперсии и стандартного отклонения

In [ ]:
#Высисление некоторых статистических показателей о массиве

In [8]:
import numpy as np
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [9]:
np.mean(matrix)

5.0

In [10]:
np.var(matrix)

6.666666666666667

In [11]:
np.std(matrix)

2.581988897471611

In [14]:
matrix = np.array([
    [1, 7, 4],
    [3, 9, 6],
    [2, 8, 5]
])
#среднее значение в каждом столбце
np.mean(matrix, axis=0)

array([2., 8., 5.])

In [15]:
#среднее значение в каждом строке
np.mean(matrix, axis=1)

array([4., 6., 5.])

In [ ]:
#требуется изменить форму массива (количество строк и столбцов) без изменения значения элементов.

In [16]:
import numpy as np
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
matrix.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [17]:
matrix.size

12

In [18]:
matrix.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [19]:
matrix.reshape(-1, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [20]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Реформирование массивов

In [ ]:
#Требуется изменить форму (количество строк и столбцов) массива без изменения значений элементов

In [1]:
import numpy as np
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

In [2]:
matrix.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [3]:
matrix.size

12

In [4]:
matrix.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [5]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Транспонирование вектора в матрицу

In [ ]:
#Требуется транспонировать вектор в матрицу

In [6]:
import numpy as np
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [7]:
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [11]:
#транспонировать вектор
np.array([1, 2, 3, 4, 5, 6]).T

array([1, 2, 3, 4, 5, 6])

In [10]:
#транспонировать вектор-строку
np.array([[1, 2, 3, 4, 5, 6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])