# Глава 6 Работа с текстом(МО Крис Элбон)

# Очистка текста

In [ ]:
#даны некоторые неструктуированные текстовые данные, и требуется выполнить их элементарную очистку

In [1]:
text_data = ["     But not so.   How arrives it joy lies slain,      ",
"   And why unblooms the best hope ever sown?    ",
"    —Crass Casualty obstructs the sun and rain,   ",
"    And dicing Time for gladness casts a moan. . . .",
"  These purblind Doomsters had as readily strown    ",
"   Blisses about my pilgrimage as pain.     "]

In [3]:
strip_whitespace = [string.strip() for string in text_data]
strip_whitespace

['But not so.   How arrives it joy lies slain,',
 'And why unblooms the best hope ever sown?',
 '—Crass Casualty obstructs the sun and rain,',
 'And dicing Time for gladness casts a moan. . . .',
 'These purblind Doomsters had as readily strown',
 'Blisses about my pilgrimage as pain.']

In [4]:
remove_periods = [string.replace(".", "") for string in strip_whitespace]
remove_periods

['But not so   How arrives it joy lies slain,',
 'And why unblooms the best hope ever sown?',
 '—Crass Casualty obstructs the sun and rain,',
 'And dicing Time for gladness casts a moan   ',
 'These purblind Doomsters had as readily strown',
 'Blisses about my pilgrimage as pain']

In [6]:
def capitalizer(string):
    return string.upper()
[capitalizer(string) for string in remove_periods]

['BUT NOT SO   HOW ARRIVES IT JOY LIES SLAIN,',
 'AND WHY UNBLOOMS THE BEST HOPE EVER SOWN?',
 '—CRASS CASUALTY OBSTRUCTS THE SUN AND RAIN,',
 'AND DICING TIME FOR GLADNESS CASTS A MOAN   ',
 'THESE PURBLIND DOOMSTERS HAD AS READILY STROWN',
 'BLISSES ABOUT MY PILGRIMAGE AS PAIN']

In [ ]:
#def capitalizer(string: str) -> str:
    #return string.upper()

In [7]:
import re
def replace_letters_with_X(string):
    return re.sub(r"[a-zA-Z]", "X", string)

[replace_letters_with_X(string) for string in remove_periods]

['XXX XXX XX   XXX XXXXXXX XX XXX XXXX XXXXX,',
 'XXX XXX XXXXXXXX XXX XXXX XXXX XXXX XXXX?',
 '—XXXXX XXXXXXXX XXXXXXXXX XXX XXX XXX XXXX,',
 'XXX XXXXXX XXXX XXX XXXXXXXX XXXXX X XXXX   ',
 'XXXXX XXXXXXXX XXXXXXXXX XXX XX XXXXXXX XXXXXX',
 'XXXXXXX XXXXX XX XXXXXXXXXX XX XXXX']

# Разбор и очистка разметки HTML

In [ ]:
#даны текстовые данные с элементами HTML. Требуется извлечь только текст.

In [16]:
from bs4 import BeautifulSoup
html = """ <div class='full_name'><span style='front-weight:bold'>
Masego</span>Azra</div>
"""

In [17]:
#разбор html
soup = BeautifulSoup(html, "lxml")

In [21]:
#найти элемент div с классом "full_name", показать текст
soup.find("div", {"class": "full_name"}).text

'\nMasegoAzra'

# Удаление знаков препинания

In [ ]:
#дан признак в виде текстовых данных, требуется удалить знаки препинания

In [22]:
import unicodedata 
import sys

In [23]:
text_data = ['Hi!!!! I. Love. This. Song....',
            '10000% Agree!!!! #LoveIT',
            'Right?!?!']

In [28]:
#создать словарь знаков препинания
punctuation = dict.fromkeys(i for i in range(sys.maxunicode)
                           if unicodedata.category(chr(i)).startswith('P'))

In [30]:
#удалить знаки препинания во всех строковых значениях
[string.translate(punctuation) for string in text_data]

['Hi I Love This Song', '10000 Agree LoveIT', 'Right']

# Лексемизация текста

In [ ]:
#дан текст и требуется разбить его на отдельные слова

In [1]:
from nltk.tokenize import word_tokenize
string = "Сегодняшняя наука - это технология завтрашнего дня"
word_tokenize(string)

['Сегодняшняя', 'наука', '-', 'это', 'технология', 'завтрашнего', 'дня']

In [2]:
from nltk.tokenize import sent_tokenize
string = """Сегодняшняя наука - это технология завтрашнего дня. Завтра начинается сегодня."""
sent_tokenize(string)

['Сегодняшняя наука - это технология завтрашнего дня.',
 'Завтра начинается сегодня.']

# Удаление стоп-слов

In [3]:
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')
from nltk.tokenize import word_tokenize

string = "I am going to go to the store and park"
tokenized_words = word_tokenize(string)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


In [4]:
stop_words = stopwords.words('english')

In [5]:
[word for word in tokenized_words if word not in stop_words]

['I', 'going', 'go', 'store', 'park']

In [ ]:
#Русский

In [9]:
string = "Я бы пошел в пиццерию покушать пицы и потом в парк"
tokenized_words = word_tokenize(string)

In [14]:
stop_words = stopwords.words('russian')
print(stop_list)

['и', 'в', 'во', 'не', 'что', 'он', 'на', 'я', 'с', 'со', 'как', 'а', 'то', 'все', 'она', 'так', 'его', 'но', 'да', 'ты', 'к', 'у', 'же', 'вы', 'за', 'бы', 'по', 'только', 'ее', 'мне', 'было', 'вот', 'от', 'меня', 'еще', 'нет', 'о', 'из', 'ему', 'теперь', 'когда', 'даже', 'ну', 'вдруг', 'ли', 'если', 'уже', 'или', 'ни', 'быть', 'был', 'него', 'до', 'вас', 'нибудь', 'опять', 'уж', 'вам', 'ведь', 'там', 'потом', 'себя', 'ничего', 'ей', 'может', 'они', 'тут', 'где', 'есть', 'надо', 'ней', 'для', 'мы', 'тебя', 'их', 'чем', 'была', 'сам', 'чтоб', 'без', 'будто', 'чего', 'раз', 'тоже', 'себе', 'под', 'будет', 'ж', 'тогда', 'кто', 'этот', 'того', 'потому', 'этого', 'какой', 'совсем', 'ним', 'здесь', 'этом', 'один', 'почти', 'мой', 'тем', 'чтобы', 'нее', 'сейчас', 'были', 'куда', 'зачем', 'всех', 'никогда', 'можно', 'при', 'наконец', 'два', 'об', 'другой', 'хоть', 'после', 'над', 'больше', 'тот', 'через', 'эти', 'нас', 'про', 'всего', 'них', 'какая', 'много', 'разве', 'три', 'эту', 'моя', 'впр

In [15]:
[word for word in tokenized_words if word not in stop_words]

['Я', 'пошел', 'пиццерию', 'покушать', 'пицы', 'парк']

In [16]:
stop_words[:5]

['и', 'в', 'во', 'не', 'что']

# Выделение основ слов

In [ ]:
#получить корневые формы слов

In [17]:
from nltk.stem.porter import PorterStemmer
string = "I am humbled by this traditional meeting"
tokenized_words = word_tokenize(string)

In [18]:
porter = PorterStemmer()

In [19]:
[porter.stem(word) for word in tokenized_words]

['I', 'am', 'humbl', 'by', 'thi', 'tradit', 'meet']

In [ ]:
#Русский

In [20]:
from nltk.stem.snowball import SnowballStemmer
tokenized_words = ['рыбаки', 'рыбаков', 'рыбаками']

In [21]:
snowball = SnowballStemmer("russian")

In [22]:
[snowball.stem(word) for word in tokenized_words]

['рыбак', 'рыбак', 'рыбак']

# Лемматизация слов

In [ ]:
#даны лексемизированные слова, которые требуется собрать в синонимические ряды

In [25]:
from nltk.stem import WordNetLemmatizer

In [26]:
tokenized_words = ['go', 'went', 'gone', 'am', 'are', 'is', 'was', 'were']

In [27]:
lemmatizer = WordNetLemmatizer()

In [28]:
[lemmatizer.lemmatize(word, pos='v') for word in tokenized_words]

['go', 'go', 'go', 'be', 'be', 'be', 'be', 'be']

# Разметка слов на части речи

In [ ]:
#даны текстовые данные и требуется пометить каждое слово или символ своей частью речи

In [4]:
import nltk
from nltk import pos_tag
from nltk import word_tokenize
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger.zip.


True

In [5]:
text_data = "Chris loved outdoor running"
text_tagged = pos_tag(word_tokenize(text_data))
text_tagged

[('Chris', 'NNP'), ('loved', 'VBD'), ('outdoor', 'RP'), ('running', 'VBG')]

In [ ]:
#NNP  имя собственное, единственное число
#NN  существительное, единственное число или неисчисляемое
#RB  наречие
#VBD глагол, прошедшее время
#VBG глагол, герундий или причастие настоящего времени
#JJ прилагательное
#PRP личное местоимение

In [6]:
[word for word, tag in text_tagged if tag in ['NN', 'NNS', 'NNP', 'NNPS']]

['Chris']

In [ ]:
#MultiLabelBinarizer удобнее всего использовать в том случае если вы хотите 
#получить "One-Hot-Encoded" данные из данных представленных в виде списка или кортежа.

In [7]:
import nltk
from sklearn.preprocessing import MultiLabelBinarizer
tweets = ["I am eating a burrito for breakfast",  
          "Political science ia an amazing field", 
          "San Francisco is an awesome city"]

In [8]:
tagged_tweets = []
for tweet in tweets:
    tweet_tag = nltk.pos_tag(word_tokenize(tweet))
    tagged_tweets.append([tag for word, tag in tweet_tag])

In [9]:
one_hot_multi = MultiLabelBinarizer()
one_hot_multi.fit_transform(tagged_tweets)

array([[1, 1, 0, 1, 0, 1, 1, 1, 0],
       [1, 0, 1, 1, 0, 0, 0, 0, 0],
       [1, 0, 1, 1, 1, 0, 0, 0, 1]])

In [10]:
#показать имена признаков
one_hot_multi.classes_

array(['DT', 'IN', 'JJ', 'NN', 'NNP', 'PRP', 'VBG', 'VBP', 'VBZ'],
      dtype=object)

In [15]:
import nltk
from nltk.corpus import brown
from nltk.tag import UnigramTagger
from nltk.tag import BigramTagger
from nltk.tag import TrigramTagger
nltk.download('brown')

[nltk_data] Downloading package brown to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\brown.zip.


True

In [16]:
sentences = brown.tagged_sents(categories='news')
train = sentences[:4000]
test = sentences[4000:]

In [17]:
unigram =UnigramTagger(train)
bigram = BigramTagger(train, backoff=unigram)
trigram = TrigramTagger(train, backoff=bigram)

In [18]:
#показать точность
trigram.evaluate(test)

0.8174734002697437

# Кодирование текста в качестве мешка слов

In [ ]:
#даны текстовые данные  и требуется создать набор признаков, указывающих на количество вхождений 
#определенного слова в текст наблюдения

In [19]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer

In [20]:
text_data = np.array(['Бразилия - моя любовь. Бразилия!',
                     'Швеция - лучше',
                     'Германия бьет обоих'])
count = CountVectorizer()
bag_of_word = count.fit_transform(text_data)

In [21]:
bag_of_word

<3x8 sparse matrix of type '<class 'numpy.int64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [22]:
bag_of_word.toarray()

array([[2, 0, 0, 0, 1, 1, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 1],
       [0, 1, 1, 0, 0, 0, 1, 0]], dtype=int64)

In [23]:
#показать имена признаков
count.get_feature_names()

['бразилия', 'бьет', 'германия', 'лучше', 'любовь', 'моя', 'обоих', 'швеция']

In [25]:
count_2gram = CountVectorizer(ngram_range=(1,2), stop_words='english', vocabulary=['бразилия'])
bag = count_2gram.fit_transform(text_data)                              
bag.toarray()

array([[2],
       [0],
       [0]], dtype=int64)

In [26]:
count_2gram.vocabulary

['бразилия']

# Взвешивание важности слов

In [ ]:
#требуется мешок слов, но со словами взвешенными по их важности для наблюдения

In [27]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

In [28]:
text_data = np.array(['Бразилия - моя любовь. Бразилия!',
                     'Швеция - лучше',
                     'Германия бьет обоих'])

In [29]:
tfidf = TfidfVectorizer()
feature_mmatrix = tfidf.fit_transform(text_data)

In [30]:
feature_mmatrix

<3x8 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [31]:
feature_mmatrix.toarray()

array([[0.81649658, 0.        , 0.        , 0.        , 0.40824829,
        0.40824829, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.70710678, 0.        ,
        0.        , 0.        , 0.70710678],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.        ,
        0.        , 0.57735027, 0.        ]])

In [33]:
tfidf.vocabulary_

{'бразилия': 0,
 'моя': 5,
 'любовь': 4,
 'швеция': 7,
 'лучше': 3,
 'германия': 2,
 'бьет': 1,
 'обоих': 6}