# 1.1 Создание вектора

In [1]:
#Требуется создать вектор

In [7]:
import numpy as np
#Создать вектор как строку
vector_row = np.array([1, 2, 3])
print('Создание вектора в виде строки ', vector_row)
vector_column = np.array([
    [1],
    [2],
    [3]
])
print('Создание вектора как столбец\n', vector_column)

Создание вектора в виде строки  [1 2 3]
Создание вектора как столбец
 [[1]
 [2]
 [3]]


In [10]:
print('Превращение столбца в строку через транспонирование', vector_column.T)

Превращение столбца в строку через транспонирование [[1 2 3]]


# 1.2 Создание матрицы

In [11]:
#Требуется создать матрицу

In [17]:
import numpy as np
#Создать матрицу
matrix = np.array([
    [1, 2],
    [1, 2],
    [1, 2]
])
print('Созданная матрица\n', matrix)

Созданная матрица
 [[1 2]
 [1 2]
 [1 2]]


In [20]:
#Не рекомендуется использовать матричную структуру
matrix_object = np.mat([
    [1, 2],
    [1, 2],
    [1, 2]
])
print('Созданная матрица без array\n', matrix_object)

Созданная матрица без array
 [[1 2]
 [1 2]
 [1 2]]


# 1.3 Создание разряженной матрицы

In [ ]:
#Имеются данные с очень малым количеством ненулевых значений, которые требуется эффективно представить

In [5]:
import numpy as np
from scipy import sparse
matrix = np.array([
    [0, 0],
    [0, 1],
    [3, 0]
])
#Создаем сжатую разряженную матрицу-строку (CSR - матрицу)
matrix_sparse = sparse.csr_matrix(matrix)
print('matrix_sparse=\n', matrix_sparse)

matrix_sparse=
   (1, 1)	1
  (2, 0)	3


# 1.4 Выбор элементов

In [1]:
#Требуется выбрать один или несколько элементов  в векторе или матрице

In [6]:
import numpy as np
vector = np.array([1, 2, 3, 4, 5, 6])
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
#выбрать третий элемент вектора
vector[2]

3

In [7]:
#выбрать вторую строку второй столбец матрицы
matrix[1, 1]

5

In [8]:
#выбрать все элементы вектора
vector[:]

array([1, 2, 3, 4, 5, 6])

In [9]:
#выбрать все впроть до третьего элемента включительно
vector[:3]

array([1, 2, 3])

In [10]:
#выбрать все после третьего элемента 
vector[3:]

array([4, 5, 6])

In [11]:
#выбрать последний элемент
vector[-1]

6

In [12]:
#выбрать первые две строки и все столбцы матрицы
matrix[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
#выбрать все строки и второй столбец
matrix[:, 1:2]

array([[2],
       [5],
       [8]])

# 1.5 Описание матрицы

In [ ]:
#Требуется описать форму, размер и размерность матрицы

In [ ]:
#использовать shape, size, ndim

In [1]:
import numpy as np
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

In [2]:
#взглянуть на количество строк и столбцов
matrix.shape

(3, 4)

In [3]:
#взглянуть на количество элементов
matrix.size

12

In [4]:
#взглянуть на количество размерностей
matrix.ndim

2

# 1.6 Применение операций к элементам

In [ ]:
#Требуется применить некоторую функцию к нескольким элементам массива

In [5]:
import numpy as np
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [6]:
#Создать функцию
add_100 = lambda i: i + 100
#Создать векторизованную функцию
vectorized_add_100 = np.vectorize(add_100)

In [7]:
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [8]:
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

# Нахождение максимального и минимального значений

In [ ]:
#Требуется найти максимальное и минимальное значение в массиве

In [1]:
import numpy as np
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [2]:
np.max(matrix)

9

In [3]:
np.min(matrix)

1

In [4]:
#максимальный элемент в каждом столбце
np.max(matrix, axis=0)

array([7, 8, 9])

In [5]:
#максимальный элемент в каждой строке
np.max(matrix, axis=1)

array([3, 6, 9])

In [6]:
matrix = np.array([
    [1, 7, 4],
    [3, 9, 6],
    [2, 8, 5]
])
#максимальный элемент в каждом столбце
np.max(matrix, axis=0)

array([3, 9, 6])

In [7]:
matrix = np.array([
    [1, 7, 4],
    [3, 9, 6],
    [2, 8, 5]
])
#максимальный элемент в каждой строке
np.max(matrix, axis=1)

array([7, 9, 8])

# Вычисление среднего значения, дисперсии и стандартного отклонения

In [ ]:
#Высисление некоторых статистических показателей о массиве

In [8]:
import numpy as np
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [9]:
np.mean(matrix)

5.0

In [10]:
np.var(matrix)

6.666666666666667

In [11]:
np.std(matrix)

2.581988897471611

In [14]:
matrix = np.array([
    [1, 7, 4],
    [3, 9, 6],
    [2, 8, 5]
])
#среднее значение в каждом столбце
np.mean(matrix, axis=0)

array([2., 8., 5.])

In [15]:
#среднее значение в каждом строке
np.mean(matrix, axis=1)

array([4., 6., 5.])

In [ ]:
#требуется изменить форму массива (количество строк и столбцов) без изменения значения элементов.

In [16]:
import numpy as np
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
matrix.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [17]:
matrix.size

12

In [18]:
matrix.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [19]:
matrix.reshape(-1, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [20]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Реформирование массивов

In [ ]:
#Требуется изменить форму (количество строк и столбцов) массива без изменения значений элементов

In [1]:
import numpy as np
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
    [10, 11, 12]
])

In [2]:
matrix.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [3]:
matrix.size

12

In [4]:
matrix.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [5]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Транспонирование вектора в матрицу

In [ ]:
#Требуется транспонировать вектор в матрицу

In [6]:
import numpy as np
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [7]:
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [11]:
#транспонировать вектор
np.array([1, 2, 3, 4, 5, 6]).T

array([1, 2, 3, 4, 5, 6])

In [10]:
#транспонировать вектор-строку
np.array([[1, 2, 3, 4, 5, 6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

# Сглаживание матрицы

In [ ]:
#преобразовать матрицу в одномерный массив

In [2]:
import numpy as np
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
#сгладить матрицу
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
#альтернатива
matrix.reshape(1,-1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

# Нахождение ранга матрицы

In [ ]:
#узнать ранг матрицы

In [4]:
import numpy as np
matrix = np.array([
    [1, 1, 1],
    [1, 1, 10],
    [1, 1, 15]
])
np.linalg.matrix_rank(matrix)

2

# Вычисление определителя матрицы

In [ ]:
#узнать определитель матрицы

In [5]:
import numpy as np
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
np.linalg.det(matrix)

-9.51619735392994e-16

# Получение диагональной матрицы

In [ ]:
#Требуется получить элементы главной диагонали матрицы

In [1]:
import numpy as np
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
matrix.diagonal()

array([1, 5, 9])

In [2]:
#Вернуть диагональ на одну выше данной диагонали
matrix.diagonal(offset=1)

array([2, 6])

In [3]:
matrix.diagonal(offset=-1)

array([4, 8])

In [5]:
np.diag(matrix)

array([1, 5, 9])

In [7]:
np.diag(matrix, k=1)

array([2, 6])

# Вычисление следа матрицы

In [ ]:
#Требуется вычислить след матрицы (сумма элементов главной диагонали)

In [8]:
import numpy as np
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
matrix.trace()

15

In [9]:
sum(matrix.diagonal())

15

# Нахождение собственных значений и собственных векторов

In [ ]:
#Найти собственные значения и собственные векторы квадратной матрицы
# Av = Lv         где А - квадратная матрица, L - собственное значение, v - собственный вектор

In [10]:
import numpy as np
matrix = np.array([
    [1, -1, 3],
    [1, 1, 6],
    [3, 8, 9]
])

In [11]:
#Вычислить собственные значения и собственные векторы
eigenvalues, eigenvectors = np.linalg.eig(matrix)

In [12]:
#Взглянуть на собственные значения
eigenvalues

array([13.55075847,  0.74003145, -3.29078992])

In [13]:
#Взглянуть на собственные векторы
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

# Вычисление скалярных произведений

In [ ]:
#Требуется вычислить скалярное произведение двух векторов
#(1*4+2*5+3*6)

In [14]:
import numpy as np
vectir_a = np.array([1, 2, 3])
vector_b = np.array([4, 5, 6])
#Вычислить скалярное произведение
np.dot(vectir_a, vector_b)

32

In [15]:
vectir_a @ vector_b

32

# Сложение и вычитание матриц

In [ ]:
#Требуется сложить и вычесть две матрицы

In [1]:
import numpy as np
matrix_a = np.array([
    [1, 1, 1],
    [1, 1, 1],
    [1, 1, 2]
])
matrix_b = np.array([
    [1, 3, 1],
    [1, 3, 1],
    [1, 3, 8]
])

In [2]:
#Сложить две матрицы
np.add(matrix_a, matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [3]:
matrix_a + matrix_b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [4]:
#Вычесть из одной матрицы другую
np.subtract(matrix_a, matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [5]:
matrix_a - matrix_b

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [9]:
import numpy as np
matrix_a = np.array(
    5
)
matrix_b = np.array([
    [1, 3, 1],
    [1, 3, 1],
    [1, 3, 8]
])
matrix_a + matrix_b

array([[ 6,  8,  6],
       [ 6,  8,  6],
       [ 6,  8, 13]])

# Умножение матриц

In [ ]:
#Требуется перемножить матрицы

In [11]:
import numpy as np
matrix_a = np.array([
    [1, 1],
    [1, 2]
])
matrix_b = np.array([
    [1, 3],
    [1, 2],
])

In [12]:
#Перемножить матрицы
np.dot(matrix_a, matrix_b)

array([[2, 5],
       [3, 7]])

In [13]:
matrix_a @ matrix_b

array([[2, 5],
       [3, 7]])

In [14]:
matrix_a * matrix_b

array([[1, 3],
       [1, 4]])

# Обращение матрицы

#Вычислить обратную квадратичную матрицу
\begin{equation*}
A * A^{-1} = E
\end{equation*}
\begin{equation*}
A^{-1} * A = E
\end{equation*}

In [ ]:
import numpy as np
matrix = np.array([
    [1, 4],
    [2, 5]
])

In [17]:
#Вычислить обратную матрицу
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [20]:
matrix @ np.linalg.inv(matrix)

array([[1., 0.],
       [0., 1.]])

In [23]:
matrix1 = np.array([
    [1.5, 400],
    [2.7, 5.9]
])

matrix1 @ np.linalg.inv(matrix1)

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

# Генерирование случайных значений

In [ ]:
#Требуется сгенерировать псевдослучайные значения

In [25]:
import numpy as np
#задаем начальное значение для генератора псевдо случайных чисел
np.random.seed(0)
#сгенерировать три случайных вещественных числа между 0 и 1
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [27]:
np.random.random((3, 5))

array([[0.54488318, 0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492, 0.56804456],
       [0.92559664, 0.07103606, 0.0871293 , 0.0202184 , 0.83261985]])

In [28]:
#сгенерировать три случайных целых числа между  1 и 10 
np.random.randint(0, 11, 3)

array([0, 2, 3])

In [29]:
np.random.randint(0, 11, (2, 5))

array([[8, 1, 3, 3, 3],
       [7, 0, 1, 9, 9]])

In [30]:
#извлечь три числа из нормального распределения со средним равным 0.0 и стандартным отклонением равным 1.0
np.random.normal(0.0, 1.0, 3)

array([ 0.03343893,  0.68056724, -1.56349669])

In [31]:
#извлечь три числа из логистического распределения со средним равным 0.0 и масштабом равным 1.0
np.random.logistic(0.0, 1.0, 3)

array([ 1.23237331, -0.17585043,  0.27546455])

In [32]:
#извлечь три числа, которые больше или равны 1.0 и меньше 2.0
np.random.uniform(1.0, 2.0, 3)

array([1.0187898 , 1.6176355 , 1.61209572])

In [33]:
#создание матрицы из нормального распределения
np.random.randn(3, 4)

array([[-0.56669762,  0.56644004,  0.14926509, -1.078278  ],
       [ 1.39547227,  1.78748405, -0.56951726,  0.17538653],
       [-0.46250554, -1.0858006 ,  0.63973599, -0.38586334]])